# 로컬 개발용 설정 (git에 올리지 마세요!)
spring:
  datasource:
    url: jdbc:postgresql://festa-ieum.com:5454/ieum-db
    username: ieum
    password: ieum1334!

tour-api:
  baseUrl: https://apis.data.go.kr/B551011/KorService2
  service-key: 322e530c75f9c8df08b2302da8e51cf93bc1d45b5f5c285e6ca8432a45727562
